import { Property, Room, Reservation, AddOn, DashboardStats } from './types';

export const mockProperties: Property[] = [
  {
    id: 'prop-1',
    name: 'Grand Plaza Hotel',
    address: '123 Main Street',
    city: 'Mumbai',
    state: 'Maharashtra',
    country: 'India',
    zipCode: '400001',
    image: 'https://images.unsplash.com/photo-1566073771259-6a8506099945?w=800&q=80',
    totalRooms: 50,
    availableRooms: 32,
    rating: 4.5,
    amenities: ['WiFi', 'Swimming Pool', 'Gym', 'Restaurant', 'Spa', 'Parking', 'Room Service', 'Conference Room'],
    propertyType: 'Hotel',
    addedOn: '2024-06-15',
    contactEmail: 'contact@grandplaza.com',
    contactPhone: '+91 22 2345 6789',
    checkInTime: '14:00',
    checkOutTime: '11:00',
    description: 'Luxury 5-star hotel in the heart of Mumbai with world-class amenities and stunning city views.',
  },
  {
    id: 'prop-2',
    name: 'Ocean View Resort',
    address: '45 Beach Road',
    city: 'Goa',
    state: 'Goa',
    country: 'India',
    zipCode: '403001',
    image: 'https://images.unsplash.com/photo-1582719508461-905c673771fd?w=800&q=80',
    totalRooms: 80,
    availableRooms: 45,
    rating: 4.8,
    amenities: ['WiFi', 'Private Beach', 'Swimming Pool', 'Water Sports', 'Restaurant', 'Bar', 'Spa', 'Kids Club'],
    propertyType: 'Resort',
    addedOn: '2024-03-22',
    contactEmail: 'reservations@oceanview.com',
    contactPhone: '+91 832 234 5678',
    checkInTime: '15:00',
    checkOutTime: '12:00',
    description: 'Beachfront resort offering pristine beaches, water sports, and relaxation in the tropical paradise of Goa.',
  },
  {
    id: 'prop-3',
    name: 'Mountain Retreat',
    address: '789 Hill Station Road',
    city: 'Shimla',
    state: 'Himachal Pradesh',
    country: 'India',
    zipCode: '171001',
    image: 'https://images.unsplash.com/photo-1520250497591-112f2f40a3f4?w=800&q=80',
    totalRooms: 30,
    availableRooms: 18,
    rating: 4.3,
    amenities: ['WiFi', 'Fireplace', 'Mountain View', 'Hiking Trails', 'Restaurant', 'Bonfire Area', 'Library'],
    propertyType: 'Boutique Hotel',
    addedOn: '2024-09-10',
    contactEmail: 'stay@mountainretreat.com',
    contactPhone: '+91 177 234 5678',
    checkInTime: '13:00',
    checkOutTime: '10:00',
    description: 'Charming boutique hotel nestled in the Himalayas, perfect for nature lovers and adventure seekers.',
  },
];

export const mockRooms: Record<string, Room[]> = {
  'prop-1': [
    {
      id: 'room-1-1',
      propertyId: 'prop-1',
      name: 'Deluxe King Room',
      type: 'Deluxe',
      pricePerNight: 5500,
      maxGuests: 2,
      amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Room Service'],
      image: 'https://images.unsplash.com/photo-1631049307264-da0ec9d70304?w=800&q=80',
      isAvailable: true,
    },
    {
      id: 'room-1-2',
      propertyId: 'prop-1',
      name: 'Premium Suite',
      type: 'Suite',
      pricePerNight: 12000,
      maxGuests: 4,
      amenities: ['WiFi', 'AC', 'TV', 'Mini Bar', 'Room Service', 'Jacuzzi', 'Living Area'],
      image: 'https://images.unsplash.com/photo-1618773928121-c32242e63f39?w=800&q=80',
      isAvailable: true,
    },
    {
      id: 'room-1-3',
      propertyId: 'prop-1',
      name: 'Standard Twin Room',
      type: 'Standard',
      pricePerNight: 3500,
      maxGuests: 2,
      amenities: ['WiFi', 'AC', 'TV'],
      image: 'https://images.unsplash.com/photo-1566665797739-1674de7a421a?w=800&q=80',
      isAvailable: true,
    },
  ],
  'prop-2': [
    {
      id: 'room-2-1',
      propertyId: 'prop-2',
      name: 'Beach View Villa',
      type: 'Villa',
      pricePerNight: 18000,
      maxGuests: 6,
      amenities: ['WiFi', 'AC', 'TV', 'Private Pool', 'Beach Access', 'Butler Service'],
      image: 'https://images.unsplash.com/photo-1602002418082-a4443e081dd1?w=800&q=80',
      isAvailable: true,
    },
    {
      id: 'room-2-2',
      propertyId: 'prop-2',
      name: 'Ocean Suite',
      type: 'Suite',
      pricePerNight: 9500,
      maxGuests: 3,
      amenities: ['WiFi', 'AC', 'TV', 'Balcony', 'Ocean View'],
      image: 'https://images.unsplash.com/photo-1590490360182-c33d57733427?w=800&q=80',
      isAvailable: true,
    },
  ],
  'prop-3': [
    {
      id: 'room-3-1',
      propertyId: 'prop-3',
      name: 'Mountain View Cottage',
      type: 'Cottage',
      pricePerNight: 7500,
      maxGuests: 4,
      amenities: ['WiFi', 'Fireplace', 'TV', 'Mountain View', 'Breakfast Included'],
      image: 'https://images.unsplash.com/photo-1587061949409-02df41d5e562?w=800&q=80',
      isAvailable: true,
    },
    {
      id: 'room-3-2',
      propertyId: 'prop-3',
      name: 'Cozy Room',
      type: 'Standard',
      pricePerNight: 4000,
      maxGuests: 2,
      amenities: ['WiFi', 'Heater', 'TV'],
      image: 'https://images.unsplash.com/photo-1595576508898-0ad5c879a061?w=800&q=80',
      isAvailable: true,
    },
  ],
};

export const mockAddOns: AddOn[] = [
  {
    id: 'addon-1',
    name: 'Airport Transfer',
    description: 'Pickup and drop from/to airport',
    price: 2500,
    selected: false,
  },
  {
    id: 'addon-2',
    name: 'Breakfast Package',
    description: 'Daily breakfast for all guests',
    price: 800,
    selected: false,
  },
  {
    id: 'addon-3',
    name: 'Spa Treatment',
    description: '60-minute relaxation massage',
    price: 3000,
    selected: false,
  },
  {
    id: 'addon-4',
    name: 'Late Checkout',
    description: 'Extend checkout until 4 PM',
    price: 1500,
    selected: false,
  },
  {
    id: 'addon-5',
    name: 'Romantic Dinner',
    description: 'Candlelight dinner for two',
    price: 4500,
    selected: false,
  },
];

export const mockReservations: Reservation[] = [
  {
    id: 'res-001',
    propertyId: 'prop-1',
    propertyName: 'Grand Plaza Hotel',
    roomId: 'room-1-1',
    roomName: 'Deluxe King Room',
    checkIn: '2026-02-10',
    checkOut: '2026-02-14',
    guestName: 'Rahul Sharma',
    guestEmail: 'rahul.sharma@email.com',
    guestPhone: '+91 9876543210',
    totalGuests: 2,
    totalAmount: 22000,
    paymentMethod: 'pay_online',
    status: 'confirmed',
    createdAt: '2026-02-01',
  },
  {
    id: 'res-002',
    propertyId: 'prop-2',
    propertyName: 'Ocean View Resort',
    roomId: 'room-2-1',
    roomName: 'Beach View Villa',
    checkIn: '2026-02-15',
    checkOut: '2026-02-18',
    guestName: 'Priya Patel',
    guestEmail: 'priya.patel@email.com',
    guestPhone: '+91 9876543211',
    totalGuests: 4,
    totalAmount: 54000,
    paymentMethod: 'pay_at_hotel',
    status: 'pending',
    createdAt: '2026-02-02',
  },
  {
    id: 'res-003',
    propertyId: 'prop-1',
    propertyName: 'Grand Plaza Hotel',
    roomId: 'room-1-2',
    roomName: 'Premium Suite',
    checkIn: '2026-02-06',
    checkOut: '2026-02-08',
    guestName: 'Amit Kumar',
    guestEmail: 'amit.kumar@email.com',
    guestPhone: '+91 9876543212',
    totalGuests: 3,
    totalAmount: 24000,
    paymentMethod: 'pay_online',
    status: 'checked_in',
    createdAt: '2026-01-28',
  },
  {
    id: 'res-004',
    propertyId: 'prop-3',
    propertyName: 'Mountain Retreat',
    roomId: 'room-3-1',
    roomName: 'Mountain View Cottage',
    checkIn: '2026-02-20',
    checkOut: '2026-02-25',
    guestName: 'Neha Singh',
    guestEmail: 'neha.singh@email.com',
    guestPhone: '+91 9876543213',
    totalGuests: 2,
    totalAmount: 37500,
    paymentMethod: 'pay_online',
    status: 'confirmed',
    createdAt: '2026-02-03',
  },
  {
    id: 'res-005',
    propertyId: 'prop-2',
    propertyName: 'Ocean View Resort',
    roomId: 'room-2-2',
    roomName: 'Ocean Suite',
    checkIn: '2026-01-28',
    checkOut: '2026-01-31',
    guestName: 'Vikram Reddy',
    guestEmail: 'vikram.reddy@email.com',
    guestPhone: '+91 9876543214',
    totalGuests: 2,
    totalAmount: 28500,
    paymentMethod: 'pay_at_hotel',
    status: 'checked_out',
    createdAt: '2026-01-20',
  },
];

export const mockDashboardStats: DashboardStats = {
  totalBookings: 156,
  totalRevenue: 2450000,
  occupancyRate: 72,
  pendingBookings: 12,
  todayCheckIns: 8,
  todayCheckOuts: 5,
};
